// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACs177lg7n9_k0J1MRCTL1i0itykZWiWU',
    appId: '1:969289430171:web:f5e976c04419176804423e',
    messagingSenderId: '969289430171',
    projectId: 'betogether-154f6',
    authDomain: 'betogether-154f6.firebaseapp.com',
    storageBucket: 'betogether-154f6.firebasestorage.app',
    measurementId: 'G-Z8NRQQK1QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgrscrXP6k8f5XAAxbNaZja0la0b89D18',
    appId: '1:969289430171:android:bc82522a1c6209bb04423e',
    messagingSenderId: '969289430171',
    projectId: 'betogether-154f6',
    storageBucket: 'betogether-154f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZfoj1vGCknJEQuUSQwJ-pUY1L0NfQfhg',
    appId: '1:969289430171:ios:30f3271da1dc9b4f04423e',
    messagingSenderId: '969289430171',
    projectId: 'betogether-154f6',
    storageBucket: 'betogether-154f6.firebasestorage.app',
    iosBundleId: 'com.example.betogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZfoj1vGCknJEQuUSQwJ-pUY1L0NfQfhg',
    appId: '1:969289430171:ios:30f3271da1dc9b4f04423e',
    messagingSenderId: '969289430171',
    projectId: 'betogether-154f6',
    storageBucket: 'betogether-154f6.firebasestorage.app',
    iosBundleId: 'com.example.betogether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACs177lg7n9_k0J1MRCTL1i0itykZWiWU',
    appId: '1:969289430171:web:55f3f6db5d94016104423e',
    messagingSenderId: '969289430171',
    projectId: 'betogether-154f6',
    authDomain: 'betogether-154f6.firebaseapp.com',
    storageBucket: 'betogether-154f6.firebasestorage.app',
    measurementId: 'G-4MY3E5BPTX',
  );
}
